version: '3.8'

services:
  dashboard-service:
    build: ./dashboard-service
    restart: unless-stopped
    ports:
      - "4002:4002"
    networks:
      - gateway-network

  prediction-service:
    build: ./prediction-service
    restart: unless-stopped
    ports:
      - "4001:4001"
    networks:
      - gateway-network

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - prediction-service
      - dashboard-service
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
