version: '3.8'

services:
  prediction-service:
    build: ./prediction-service
    ports:
      - "4001:4001"
    networks:
      - gateway-network

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - prediction-service
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
